# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=b'', max_length=50)),
                ('last_name', models.CharField(default=b'', max_length=50)),
                ('number', models.CharField(default=b'', max_length=50)),
                ('email', models.CharField(default=b'', max_length=50)),
                ('pickup_address', models.CharField(default=b'', max_length=100)),
                ('plan', models.CharField(choices=[(b'HR', b'Hourly'), (b'DY', b'Daily'), (b'MN', b'Monthly'), (b'EV', b'Event Plan')], default=b'HR', max_length=1)),
                ('driver_sex', models.CharField(choices=[(b'MA', b'Male'), (b'FE', b'Female')], default=b'CC', max_length=1)),
                ('payment', models.CharField(choices=[(b'CS', b'Cash'), (b'CC', b'Credit Card')], default=b'CC', max_length=1)),
                ('code', models.CharField(default=5041, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('home_address', models.CharField(max_length=50)),
                ('residence_years', models.CharField(max_length=50)),
                ('lasdri', models.CharField(max_length=50)),
                ('experience_years', models.CharField(max_length=50)),
            ],
        ),
    ]
