# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='code',
            field=models.CharField(default=4853, max_length=4),
        ),
        migrations.AlterField(
            model_name='contact',
            name='payment',
            field=models.CharField(choices=[(b'CS', b'Cash'), (b'CC', b'Credit Card')], default=b'CC', max_length=2),
        ),
    ]
